//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient.Serv {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Serv.INumberOfTimesService")]
    public interface INumberOfTimesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberOfTimesService/GetCounts", ReplyAction="http://tempuri.org/INumberOfTimesService/GetCountsResponse")]
        int GetCounts(string text, string strToFind);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberOfTimesService/GetCounts", ReplyAction="http://tempuri.org/INumberOfTimesService/GetCountsResponse")]
        System.Threading.Tasks.Task<int> GetCountsAsync(string text, string strToFind);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INumberOfTimesServiceChannel : ConsoleClient.Serv.INumberOfTimesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NumberOfTimesServiceClient : System.ServiceModel.ClientBase<ConsoleClient.Serv.INumberOfTimesService>, ConsoleClient.Serv.INumberOfTimesService {
        
        public NumberOfTimesServiceClient() {
        }
        
        public NumberOfTimesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NumberOfTimesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberOfTimesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberOfTimesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetCounts(string text, string strToFind) {
            return base.Channel.GetCounts(text, strToFind);
        }
        
        public System.Threading.Tasks.Task<int> GetCountsAsync(string text, string strToFind) {
            return base.Channel.GetCountsAsync(text, strToFind);
        }
    }
}
